package br.furb;

public class Main {
//DICA PROFESSOR:
	//QUANDO O USUARIO CLICA PRA INICIAR UMA RETA, INICIE O VETOR DE PONTOS DESTE ELEMENTO COM AS DUAS PRIMEIRAS
	//POSICOES JA PREENCHIDAS COM O VALOR IGUAL AO X,Y DO CLIQUE INICIAL, ISSO EVITARÁ TESTES DO TIPO: IF(ARR_PONTOS.LENGTH==1) GL.POINTS
	public static void main(String[] args) {
		new Frame().setVisible(true);
	}
	
}
